import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav";

const lato = Lora({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${lato.className} h-full`}
    >
      <body className="min-h-full flex flex-col p-6">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
